lib/mock-directive/mock-directive.ts
Found a case where the annotations were returned instead of the mock directive.
=> fix: Fix bad return value from mock-directive

lib/common/reflect.ts, lib/mock-directive/mock-directive.spec.ts
There is yet *another* way to add inputs on an Angular directive. I found that `FormConrolDirective` used a `propDecorators` object. Looking at the [source](https://github.com/angular/angular/blob/master/packages/forms/src/directives/reactive_directives/form_control_directive.ts#L144), I don't see anything special about what they are doing but for whatever reason, the inputs/outputs show up under the `<DirectiveClass>.propDecorators` object.
~~TODO: Should probably consider automatically hooking up output emitters on directives like it's done with components. If people are using `@angular/forms` junk, they'll likely run into it for things like `(ngOnChange)`.~~
=> feat: Support Angular propDecorators inputs and outputs

.gitignore, lib/mock-component/mock-component.spec.ts, lib/mock-component/mock-component.ts, lib/mock-component/test-components/custom-form-control.component.ts
Allow mock component to support reactive form component: ControlValueAccessor events. 
Two methods added
__simulateTouch - lets you simulate the touch event on that reactive form component being called.
__simulateChange - lets you simulate the value change event on the reactive form component being called.
=> Update mock component allowing the use of simulated reactive forms events 

lib/mock-component/mock-component.spec.ts, lib/mock-component/mock-component.ts, lib/mock-component/test-components/child-component.component.ts
Added the ability to use ViewChild/ViewChildren etc with MockComponent. Also ensured that methods of the component are defined in the mock component, to allow spying. Created ChildComponent to test this functionality.
=> Support Angular component query decorators

lib/mock-component/mock-component.spec.ts, lib/mock-component/mock-component.ts, lib/mock-module/mock-module.ts
Found interesting case: with nested components undefined blocks could cause "Can't bind to 'ngTemplateOutlet' since it isn't a known property of 'template'" error - and the problem was cased due to CommonModule wasn't injected properly to mocked module.
=> Support of latest ngTemplateOutlet API + proper injection of CommonModule to mocked modules

README.md, lib/mock-module/mock-module.spec.ts, lib/mock-module/mock-module.ts, lib/mock-module/test-fixtures.ts
There’re some NgModules with providers like
* `RouterModule.forRoot`
* `RouterModule.forChild`
* `TinymceModule.withConfig`
They return `ModuleWithProviders` instead of `NgModule` and it requires special handling.
=> Support mock of ModuleWithProviders

build-with-supported-angluars.sh, lib/mock-module/mock-module.ts, package-lock.json, package.json
Added more flexible way to detect system provides, which we shouldn't mock / replace.
=> #42: Issue with Animations Library

lib/mock-component/mock-component.ts
Added the capability for providing your own, custom decorator meta-data (useful when wanting to mock Components from ionicframework).
Since ionic framework (https://ionicframework.com/) is build using web components (using stencil.js: https://stenciljs.com/), ng-mocks can't seem to derive the decorator meta-data (since there isn't any) - this allows the user of ng-mocks to manually provide it:
**Usage:**
Add ionic framework to an existing / new Angular application:
```ng add @ionic/angular```
_`app.component.html`-file:_
```html
<ion-button (ionFocus)="focus()">Test</ion-button>
```
_`app.component.ts`-file:_
```typescript
import { Component } from '@angular/core';
@Component({
selector: 'app-root',
templateUrl: './app.component.html',
styleUrls: ['./app.component.scss']
})
export class …
```
=> Ionic support

lib/mock-component/mock-component.ts, lib/mock-directive/mock-directive.ts, tsconfig.json
Angular 8 switches TS target to `es2015` and primary bundle contains ES6 class declaration and because of that method mocking in `MockDirective` and `MockComponent` no longer works.
The problem is that native JS class methods are not enumerable and thus `Object.keys` cannot be used. `Object.getOwnPropertyNames` should be used instead to enumerate non enumerable properties.
PR contains changes needed to make mocking work in es2015 environment and are backwards compatible.
=> fix: es2015 class declaration method mocking

lib/mock-pipe/index.ts
Hi,
I would like to have ability to import MockPipes directly from ng-mocks, without using full path.
=> Export both MockPipe and MockPipes

docker/docker-entrypoint.sh, index.ts, lib/mock-module/mock-module.spec.ts, lib/mock-module/mock-module.ts, lib/mock-module/test-fixtures.ts, lib/mock-service/index.ts, lib/mock-service/mock-service.spec.ts, lib/mock-service/mock-service.ts
The goal is not to provide an empty object as a provider, but to try to simulate existing methods.
What I tried to do was is to clone https://github.com/gothinkster/angular-realworld-example-app and to add a simple test which checks that app.component is rendered. And found that it fails with the error `TypeError: this.userService.populate is not a function` and I think if we mock at least methods of providers we should solve almost majority of issues except chaining `this.userService.populate().test()` but that's impossible without a metadata parser.
```typescript
import {TestBed} from '@angular/core/testing';
import {BrowserModule} from '@angular/platform-browser';
import {AppRoutingModule} from 'app/app-routing.module';
import {AppComponent} from 'app/app.component';
import …
```
=> feat: Mocking service

lib/mock-module/mock-module.spec.ts, lib/mock-module/mock-module.ts
It has sensetive providers such as:
* Application Initializer
* ApplicationInitStatus
* localeId
=> fix: never mock ApplicationModule

e2e/mock-builder-keeps-application-module/fixtures.components.ts, e2e/mock-builder-keeps-application-module/fixtures.modules.ts, e2e/mock-builder-keeps-application-module/test.spec.ts, lib/mock-builder/mock-builder.ts
By default all providers of ApplicationModule will be kept until they're explicitly mocked / replaced.
=> feat(mock-builder): ApplicationModule providers

e2e/normal-usage-after-mock-builder/fixtures.components.ts, e2e/normal-usage-after-mock-builder/fixtures.modules.ts, e2e/normal-usage-after-mock-builder/fixtures.services.ts, e2e/normal-usage-after-mock-builder/test.spec.ts, lib/mock-module/mock-module.ts
In case of the skipMock we should respect the original class.
=> test: assure no leftovers after MockBuilder

README.md, e2e/spies/fixtures.components.ts, e2e/spies/fixtures.modules.ts, e2e/spies/fixtures.providers.ts, e2e/spies/test.spec.ts, jasmine.ts, jest.ts, karma.conf.ts, lib/common/Mock.ts, lib/mock-component/mock-component.spec.ts, lib/mock-directive/mock-directive.spec.ts, lib/mock-helper/mock-helper.ts, lib/mock-service/mock-service.spec.ts, lib/mock-service/mock-service.ts, tsconfig.json
=> feat: support to inject a library-related service mocker

README.md, examples/MockRender/MockRender.spec.ts, lib/mock-render/mock-render.spec.ts, lib/mock-render/mock-render.ts
now `MockRender` returns a `fixture` with a `point` property that simplifies typecheck while accessing the component instance.
=> feat: typecasted MockRender

README.md, karma-test-shim.ts, lib/mock-render/mock-render.fixtures.ts, lib/mock-render/mock-render.spec.ts, lib/mock-render/mock-render.ts
closes #102 
should be rebased after https://github.com/ike18t/ng-mocks/pull/104
=> feat: providers for MockRender

lib/mock-helper/mock-helper.spec.ts, lib/mock-helper/mock-helper.ts, lib/mock-render/mock-render.spec.ts, lib/mock-render/mock-render.ts, tests/mock-render-mirrors-component/test.spec.ts
=> feat: mock-render tries to mirror passed component

lib/mock-module/mock-module.ts, tests/issue-142/test.spec.ts
=> fix: detection of empty modules in mock process

examples/MockReactiveForms/dependency.component.ts, lib/common/Mock.ts, lib/mock-component/mock-component.ts, lib/mock-component/test-components/empty-component.component.ts, lib/mock-directive/mock-directive.ts, tests/issue-145/components.spec.ts, tests/issue-145/directives.spec.ts, tsconfig.json
in case of components we add NG_VALUE_ACCESSOR for historical reasons and this behavior wasn't changed.
closes #145
=> fix: adding NG_VALUE_ACCESSOR only when necessary

lib/common/lib.ts, lib/mock-builder/mock-builder.ts, lib/mock-component/mock-component.ts, lib/mock-directive/mock-directive.ts, lib/mock-module/mock-module.ts, lib/mock-service/mock-service.ts, tests/issues-172/test.spec.ts
=> fix: allows mocking providers of an kept component

lib/mock-render/mock-render.ts, tests/issue-266/test.spec.ts
=> fix: declarations w/o selectors are reachable with ngMocks helpers

libs/ng-mocks/src/lib/mock-helper/cva/mock-helper.change.ts, libs/ng-mocks/src/lib/mock-helper/cva/mock-helper.touch.ts, tests/ng-mocks-change/cdr-change.spec.ts, tests/ng-mocks-change/cdr-input.spec.ts, tests/ng-mocks-touch/cdr-blur.spec.ts, tests/ng-mocks-touch/cdr-touch.spec.ts
=> fix(#324): smarter touches and changes

libs/ng-mocks/src/lib/common/func.import-exists.ts, libs/ng-mocks/src/lib/mock-component/mock-component.ts, libs/ng-mocks/src/lib/mock-directive/mock-directive.ts, libs/ng-mocks/src/lib/mock-instance/mock-instance.ts, libs/ng-mocks/src/lib/mock-module/mock-module.ts, libs/ng-mocks/src/lib/mock-pipe/mock-pipe.ts, libs/ng-mocks/src/lib/mock-provider/mock-provider.ts, libs/ng-mocks/src/lib/mock-render/mock-render.ts, tests/issue-354/test.spec.ts, tslint.json
=> fix(#354): better error instead of is not in JIT mode

libs/ng-mocks/src/lib/mock-component/render/generate-template.ts, tests/issue-445/test.spec.ts
=> fix: skipping wrong query selectors #445

libs/ng-mocks/src/lib/mock-builder/mock-builder.ts, tests/issue-435/test.spec.ts
=> fix(mock-builder): overrides mock modules for platform #435

docs/articles/api/MockInstance.md, docs/articles/api/MockRender.md, examples/MockBuilder/test.deep.spec.ts, libs/ng-mocks/src/lib/mock-component/mock-component.spec.ts, libs/ng-mocks/src/lib/mock-instance/mock-instance.ts, libs/ng-mocks/src/lib/mock-render/func.reflect-template.ts, libs/ng-mocks/src/lib/mock-render/mock-render.ts, libs/ng-mocks/src/lib/mock-render/types.ts, package.json, tests/internal-vs-external/test.spec.ts, tests/issue-488/test.spec.ts, tests/mock-render-mirrors-component/test.spec.ts, tests/ng-mocks-global-exclude/test.override.spec.ts, tests/ng-mocks-global-keep/test.override.spec.ts, tests/ng-mocks-global-replace/test.override.spec.ts, tests/ng-mocks-reveal/test.spec.ts, tests/spies/test.spec.ts
=> feat(mock-render): throws on wrong usage #488

docs/articles/troubleshooting/browser-animations-module.md, docs/sidebars.js, libs/ng-mocks/src/lib/mock-helper/mock-helper.guts.ts, libs/ng-mocks/src/lib/mock-module/mock-ng-def.ts, tests/fake-async/test.spec.ts, tests/issue-222/dom-shared-styles-host.spec.ts, tests/issue-641/test.spec.ts
=> feat(core): replacing animations with noop by default #641

libs/ng-mocks/src/lib/common/core.reflect.directive-resolve.ts, libs/ng-mocks/src/lib/mock-component/mock-component.ts, libs/ng-mocks/src/lib/mock/decorate-declaration.ts, tests/issue-726/test.spec.ts
=> fix(core): supports mocks for viewProviders #726

e2e/a-jest/jest.es2015ivy.js, e2e/a-jest/jest.es5ivy.js, e2e/a-jest/package-lock.json, e2e/a-jest/package.json, e2e/a-jest/src/app/app.component.spec.ts, e2e/a-jest/src/setup-jest.ts, e2e/a-jest/tsconfig.json, e2e/a-min/jest.es2015ivy.js, e2e/a-min/jest.es5ivy.js
=> test(e2e): pure jest configuration #610

libs/ng-mocks/src/lib/common/core.helpers.ts, libs/ng-mocks/src/lib/common/core.injector.ts, libs/ng-mocks/src/lib/common/core.reflect.body-catch.ts, libs/ng-mocks/src/lib/common/mock.ts, libs/ng-mocks/src/lib/common/ng-mocks-global-overrides.ts, libs/ng-mocks/src/lib/mock-builder/promise/handle-entry-components.ts, libs/ng-mocks/src/lib/mock-helper/func.parse-provider-tokens-directives.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.attributes.ts, libs/ng-mocks/src/lib/mock-helper/template-ref/detect-template-ref.ts, libs/ng-mocks/src/lib/mock-render/func.reflect-template.ts, libs/ng-mocks/src/lib/mock-render/mock-render-factory.ts, tests/issue-1876/test.spec.ts
=> fix(mock-render): apply overrides to components with no selectors #1876

docs/articles/troubleshooting/browser-animations-module.md, e2e/a-min/docker-compose.yml, e2e/a-min/package-lock.json, e2e/a-min/package.json, libs/ng-mocks/src/lib/common/mock.ts, libs/ng-mocks/src/lib/common/ng-mocks-global-overrides.ts, libs/ng-mocks/src/lib/mock-builder/mock-builder.promise.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.console-throw.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.faster-install.ts, libs/ng-mocks/src/lib/mock-module/create-resolvers.ts, libs/ng-mocks/src/lib/mock-module/mock-module.ts, libs/ng-mocks/src/lib/mock-render/func.create-wrapper.ts, libs/ng-mocks/src/lib/mock-render/func.install-prop-reader.ts, libs/ng-mocks/src/lib/mock-render/mock-render-factory.ts, libs/ng-mocks/src/lib/mock-service/helper.create-mock-from-prototype.ts, tests/issue-1377/test.spec.ts, tests/issue-222/dom-shared-styles-host.spec.ts, tests/issue-641/test.spec.ts
=> fix(core): BrowserAnimationsModule is optional dependency now #1377

docs/articles/api/ngMocks/findTemplateRefs.md
Correct method typos in findTemplateRefs.md
see in https://ng-mocks.sudo.eu/api/ngMocks/findTemplateRefs
=> Correct method typos in findTemplateRefs.md

docs/articles/extra/with-3rd-party.md, tests-e2e/package-lock.json, tests-e2e/package.json, tests-e2e/src/issue-971/test.spec.ts, tests-e2e/src/spectator/classic.spec.ts, tests-e2e/src/spectator/standalone.spec.ts, tests-e2e/src/testing-library/classic.spec.ts, tests-e2e/src/testing-library/standalone.spec.ts
=> docs: covering spectator with standalone components #2921

e2e/a10/package.json, e2e/a11/package.json, e2e/a9/package.json, libs/ng-mocks/src/lib/mock-render/func.create-wrapper.ts, libs/ng-mocks/src/lib/mock-render/mock-render-factory.ts, package.json, tests/issue-3053/test.spec.ts
=> feat(MockRender): supports Self providers #3053

libs/ng-mocks/src/lib/mock-builder/promise/init-keep-def.ts, libs/ng-mocks/src/lib/mock-builder/promise/init-universe.ts, tests/issue-3161/exclude.spec.ts, tests/issue-3161/keep.spec.ts, tests/issue-3161/test.spec.ts
closes #3161
MockBuilder will process dependencies of standalone declarations with respect of the next configuration:
- ngMocks.globalKeep
- ngMocks.globalMock
- ngMocks.globalReplace
- ngMocks.globalExclude
=> fix(MockBuilder): respects global configuration for standalone dependencies #3161

.eslintrc.yml, libs/ng-mocks/src/lib/mock-helper/cva/mock-helper.change.ts, libs/ng-mocks/src/lib/mock-helper/cva/mock-helper.touch.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.ts, tests/ng-mocks-change/3341.spec.ts, tests/ng-mocks-change/reactive-forms.spec.ts, tests/ng-mocks-touch/3341.spec.ts, tests/ng-mocks-touch/test.spec.ts
=> feat(ngMocks): supports custom method names for change and touch #3341

libs/ng-mocks/src/lib/common/func.extract-forward-ref.ts, libs/ng-mocks/src/lib/mock-builder/mock-builder.promise.ts, libs/ng-mocks/src/lib/mock-builder/promise/extract-dep.ts, libs/ng-mocks/src/lib/mock-builder/promise/init-universe.ts, libs/ng-mocks/src/lib/mock-service/helper.resolve-provider.ts, libs/ng-mocks/src/lib/mock/clone-providers.ts, tests/issue-3791/test.spec.ts
=> fix(core): providers with useExisting will be kept if their value is a kept declaration #3778

.commitlintrc.yml, .eslintignore, .prettierignore, e2e/jest/src/tests/issue-3811/__snapshots__/test.spec.ts.snap, e2e/jest/src/tests/issue-3811/test.spec.ts, libs/ng-mocks/src/lib/mock-render/func.create-wrapper.ts, tests/issue-3811/test.spec.ts
NOTE: If you use jest snapshots it might require to update them and remove the `__ngContext__` attribute from `mock-render` nodes.
closes #3811
=> feat(MockRender): the host element doesn't have __ngContext__ attribute anymore #3811

libs/ng-mocks/src/lib/common/core.def-stack.spec.ts, libs/ng-mocks/src/lib/common/core.def-stack.ts, libs/ng-mocks/src/lib/common/func.is-mock.ts, libs/ng-mocks/src/lib/mock-builder/mock-builder.promise.ts, libs/ng-mocks/src/lib/mock-builder/promise/handle-root-providers.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.guts.ts, libs/ng-mocks/src/lib/mock-module/create-resolvers.ts, libs/ng-mocks/src/lib/mock-module/mock-module.ts, libs/ng-mocks/src/lib/mock-module/mock-ng-def.ts, libs/ng-mocks/src/lib/mock-pipe/mock-pipe.ts, libs/ng-mocks/src/lib/mock-service/helper.resolve-provider.ts, libs/ng-mocks/src/lib/mock/clone-providers.ts, libs/ng-mocks/src/lib/mock/decorate-declaration.ts, libs/ng-mocks/src/lib/mock/get-mock.ts, libs/ng-mocks/src/lib/mock/return-cached-mock.ts, tests/issue-4344/standalone.spec.ts, tests/issue-4344/test.spec.ts
=> fix(core): correct caching of touched declarations #4344

libs/ng-mocks/src/lib/mock-helper/mock-helper.stub.ts, tests/issue-4367/test.spec.ts
=> feat(MockInstance): ignores undefined properties #4367

libs/ng-mocks/src/lib/mock-builder/promise/init-ng-modules.ts, tests/issue-4613/providers.spec.ts, tests/issue-4613/test.spec.ts
=> fix(MockBuilder): imports modules with providers on root level #4613

docs/articles/guides/mock/dynamic-components.md, docs/sidebars.js, libs/ng-mocks/src/lib/common/ng-mocks-global-overrides.ts, tests-e2e/src/issue-4693/child.component.ts, tests-e2e/src/issue-4693/test.spec.ts
=> feat(core): ViewContainerRef.createComponent respects mocks #4742

libs/ng-mocks/src/lib/common/core.helpers.ts, tests/issue-5465/test.spec.ts
=> fix(core): merge of kept / mock declarations in CommonModule #5465

libs/ng-mocks/src/lib/mock-builder/promise/init-universe.ts, tests/issue-5520/test.spec.ts
=> fix(MockBuilder): touches kept modules in standalone components #5520

docs/articles/guides/libraries/ngxs.md, docs/sidebars.js
=> docs(ngxs): fixing typo in the library name #6356

libs/ng-mocks/src/lib/common/core.helpers.ts, libs/ng-mocks/src/lib/common/func.extract-deps.ts, libs/ng-mocks/src/lib/mock-builder/promise/init-universe.ts, tests/issue-6402/test.spec.ts
=> fix(MockBuilder): respects global rules as they would be chain calls #6402

docs/articles/index.md
=> docs: make clear that MockInstance.scope() is optional #7040

docs/articles/guides/mock/activated-route.md, libs/ng-mocks/src/lib/mock-builder/mock-builder.ts, tests/issue-7796/test.spec.ts
=> docs(ActivatedRoute): enhanced description #7796

libs/ng-mocks/src/lib/mock-helper/crawl/el-def-get-parent.ts, tests/issue-7216/test.spec.ts
ViewContainerRef actually returns the wrong length in case of Angular 17 Control Flow. By checking that the returned value is not null we should be safe.
Solves #7216
=> fix: unable to find instance in case of ng17 control flow

e2e/a12/jest.es2015ivy.js, e2e/a12/jest.es5ivy.js, e2e/a12/package.json, e2e/a12/src/setup-jest.ts, libs/ng-mocks/src/lib/mock-component/mock-component.spec.ts, libs/ng-mocks/src/lib/mock-component/mock-component.ts, libs/ng-mocks/src/lib/mock-component/render/generate-template.ts, tests/issue-8884/test.spec.ts
When component templates contain child templates, they are replaced with a mock template that contains a `*ngIf` this causes a failure when the component doesn't have NgIf imported.
Though this problem likely exists in some pre-angular 17 situations, it has been causing new failures to appear as people upgrade since 3rd party angular components are starting to use the new control flow syntax and no longer import `CommonModule` / `NgIf`.
Instead the mock template now uses `@if` syntax if angular is 17 or higher.
Fixes #8884
=> fix: unable to bind ngIf in angular 17+

docs/articles/guides/routing-guard.md, examples/TestRoutingGuard/can-load.spec.ts
I have added a new can-load.spec to verify that `NG_MOCKS_GUARDS` is working also with the canLoad guard. 
In addition I updated the docs to have link this the can-load.spec instaed of the can-match.spec. 
Hope this PR helps. 
Thanks for the good work. I really like using ng-mocks.
fixes #9835
=> docs: can-load guard #1008

libs/ng-mocks/src/lib/mock-helper/mock-helper.flush-test-bed.ts, tests/mock-helper-flush-test-bed/test.spec.ts
call tearDownTestingModule before setting refs to null
Fixes #9666
=> fix: 9666 Performance

CHANGELOG.md, docs/articles/api/MockInstance.md, docs/articles/api/MockRender.md, docs/articles/api/ngMocks/formatHtml.md, docs/articles/api/ngMocks/stubMember.md, docs/articles/extra/mock-form-controls.md, docs/articles/extra/quick-start.md, docs/articles/guides/directive-attribute.md, docs/articles/guides/host-directive.md, examples/TestAttributeDirective/test.spec.ts, examples/TestRoutingGuard/can-deactivate.spec.ts, tests/issue-522/test.spec.ts
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling)
The misspellings have been reported at https://github.com/jsoref/ng-mocks/actions/runs/14120574763#summary-39559936503
The action reports that the changes in this PR would make it happy: https://github.com/jsoref/ng-mocks/actions/runs/14120574891#summary-39559936665
=> docs: fixing spelling in code
