help-me-mom/ng-mocks

index.ts, lib/common/declaration.ts, lib/common/index.ts, lib/common/mock-of.decorator.spec.ts, lib/common/mock-of.decorator.ts, lib/mock-component/mock-component.ts, lib/mock-declaration/mock-declaration.ts, lib/mock-directive/mock-directive.ts, lib/mock-module/mock-module.ts, lib/mock-pipe/mock-pipe.ts, tslint.json
Also started using `Type<any>` instead of `Declarations`.
=> feat: MockOf - Include mocked class names in mock class names

README.md, lib/mock-component/mock-component.spec.ts, lib/mock-component/mock-component.ts
=> Add documentation for simulated reactive forms events

README.md
Hello @ike18t ,
This PR includes a couple touch ups to your readme I thought you may want (they're all rather inconsequential).
As an aside, I'm a big fan of this library. ng-mocks has greatly facilitated my component testing. Keep up the great work!
=> Adds some touch-ups to README

lib/mock-component/mock-component.spec.ts, lib/mock-component/mock-component.ts
Attempt to fix issue https://github.com/ike18t/ng-mocks/issues/32.
=> Adding wrappers only when necessary #32

lib/mock-module/mock-module.spec.ts, lib/mock-module/test-fixtures.ts
Hi @ike18t, please check UT for the issue we discussed in PR 35.
=> UT for https://github.com/ike18t/ng-mocks/pull/35

package.json
I know that the devDependencies should probably also be updated
to version 9, but doing ngUpdate gave me some warnings? We have a
rather big project using ng-mocks, and it seems to work without issues,
so I guess updating the peer dependencies is enough 🤓
=> Updated peer dependencies to Angular v9 🧐

lib/mock-render/mock-render.spec.ts, lib/mock-render/mock-render.ts
#67 Accept an arg to allow control of detectChanges.
=> feat(mock-render): option to detectChanges or not

.dockerignore, .travis.yml, Dockerfile, build-with-supported-angluars.sh, docker-compose.yml, docker/docker-entrypoint.d/010-install.sh, docker/docker-entrypoint.sh, e2e/injected-ng-templates/custom-injection.component.ts, examples/MockComponent/dependency.component.ts, examples/MockModule/dependency.component.ts, examples/MockRender/dependency.component.ts, karma.conf.ts, lib/mock-component/mock-component.spec.ts, lib/mock-component/mock-component.ts, lib/mock-component/test-components/template-outlet.component.ts, lib/mock-directive/mock-directive.spec.ts, package-lock.json, package.json, tests/index.ts, tsconfig.json
if you want to run tests locally - simply run `docker-compose up` container has node 10 and chrome browser. It's needed if your local node version is 12+, because some libs can't be compiled successfully on it.
=> Run tests on all versions + Docker for local testing

karma.conf.ts, lib/mock-component/mock-component.ts, tsconfig.json
=> reafactor: Get rid of tests in production build

CHANGELOG.md, lib/common/Mock.spec.ts, lib/common/Mock.ts, lib/common/mock-of.decorator.ts, lib/mock-component/mock-component.ts, lib/mock-directive/mock-directive.ts, lib/mock-module/mock-module.ts, lib/mock-pipe/mock-pipe.ts, lib/mock-service/mock-service.ts
=> fix: respect of all parents

lib/common/decorate.ts, lib/mock-component/mock-component.spec.ts, lib/mock-component/mock-component.ts, lib/mock-directive/mock-directive.spec.ts, lib/mock-directive/mock-directive.ts
=> fix: correct mocking of xxxChild(ren) decorators

README.md, lib/mock-helper/mock-helper.spec.ts, lib/mock-helper/mock-helper.ts
Should be rebased and merged after https://github.com/ike18t/ng-mocks/pull/104
=> feat: MockHelper with find, findAll and fetch

README.md, jest.ts, lib/common/Mock.spec.ts, lib/common/Mock.ts, lib/common/mock-of.decorator.ts, lib/mock-pipe/mock-pipe.ts, lib/mock-service/mock-service.spec.ts, lib/mock-service/mock-service.ts
=> feat: original instanceof and properties

lib/mock-helper/mock-helper.ts, lib/mock-service/mock-service.spec.ts, lib/mock-service/mock-service.ts
=> feat: mock-service is typed and supports overrides

e2e/module-with-factory-tokens/fixtures.ts, e2e/module-with-factory-tokens/test.spec.ts, e2e/module-with-tokens/fixtures.ts, e2e/module-with-tokens/test.spec.ts, lib/mock-builder/mock-builder.ts, lib/mock-module/mock-module.ts
=> fix: better coverage for tokens

lib/mock-component/mock-component.ts, lib/mock-directive/mock-directive.ts, lib/mock-helper/mock-helper.ts, lib/mock-module/mock-module.ts, lib/mock-pipe/mock-pipe.ts, lib/mock-render/mock-render.ts
=> fix: throw a human readable error during resolve

README.md
=> docs: fixing docs description for TestingModule

lib/mock-module/mock-module.spec.ts, lib/mock-module/mock-module.ts
=> fix: respect of WithProviders without providers

lib/mock-builder/mock-builder.ts, lib/mock-module/mock-module.spec.ts, lib/mock-module/mock-module.ts, lib/mock-service/mock-service.spec.ts, lib/mock-service/mock-service.ts, tests/issue-151/app/app-routing.module.ts, tests/issue-151/app/app.component.ts, tests/issue-151/app/app.module.ts, tests/issue-151/app/hello.component.ts, tests/issue-151/app/hello.module.ts, tests/issue-151/test.spec.ts, tslint.json
=> fix: respect mocks in tokens with useValue

README.md, lib/mock-module/mock-module.ts, package.json, tsconfig.json
=> fix: building es5 only that supports es2015

lib/mock-component/mock-component.ts, lib/mock-directive/mock-directive.ts, lib/mock-render/mock-render.ts, tests/issue-145/components.spec.ts, tests/issue-145/directives.spec.ts, tests/issue-157/test.spec.ts, tests/issue-167/NG_VALIDATORS.spec.ts, tests/issue-167/component.spec.ts, tests/issue-167/directive.spec.ts
=> fix: injection of NG_VALIDATORS and NgControl

README.md, examples/MockInstance/test.spec.ts, examples/NG_MOCKS/NG_MOCKS.spec.ts, index.ts, lib/common/Mock.ts, lib/common/mock-of.decorator.ts, lib/mock-builder/mock-builder.ts, lib/mock-component/mock-component.ts, lib/mock-directive/mock-directive.ts, lib/mock-instance/index.ts, lib/mock-instance/mock-instance.ts, lib/mock-module/mock-module.ts, lib/mock-service/mock-service.ts, tests/issue-170/test.spec.ts
=> feat: extending mocked things via MockInstance

README.md, lib/common/lib.ts, lib/common/ng-mocks-universe.ts, lib/mock-builder/mock-builder.ts, lib/mock-component/mock-component.ts, lib/mock-directive/mock-directive.ts, lib/mock-module/mock-module.ts, lib/mock-pipe/mock-pipe.ts, lib/mock-service/mock-service.spec.ts, lib/mock-service/mock-service.ts, tests/issue-173/test.spec.ts
=> fix: unexpected value '[object Object]' exported by the module

lib/mock-service/mock-service.ts, tests/issue-177/test.spec.ts
=> fix: mocking getter and setters of services

lib/mock-module/mock-module.ts, tests/issue-178/test.spec.ts
=> fix: mocking imports after declarations

README.md, examples/MAIN/test.spec.ts
=> docs: a better starting example

lib/common/decorate.ts, lib/mock-component/mock-component.ts, lib/mock-directive/mock-directive.ts, tests/issue-181/test.spec.ts
closes #181
Signed-off-by: MG <m@sudo.eu>
=> fix: cannot combine @Input decorators with query decorators

README.md, lib/mock-helper/mock-helper.ts, lib/mock-service/mock-service.spec.ts, tests/issue-166/test.spec.ts
=> fix: generic type constraint for ngMocks.stub tedious to write

lib/mock-component/mock-component.ts
=> fix: cache break of MockComponent

README.md, examples/MockBuilder/MockBuilder.spec.ts, examples/NG_MOCKS/NG_MOCKS.spec.ts, lib/mock-builder/mock-builder.ts
=> fix: mocking private service in component

lib/common/ng-mocks-universe.ts, lib/mock-builder/mock-builder-stash.ts, lib/mock-helper/mock-helper.guts.ts, lib/mock-module/mock-ng-def.ts, lib/mock-service/mock-provider.ts, tests/get-mocked-ng-def-of/test.spec.ts, tests/issue-241/fixtures.ts, tests/issue-241/test.builder.spec.ts, tests/issue-241/test.classic.spec.ts, tests/issue-241/test.guts.spec.ts, tests/issue-241/test.real.spec.ts
=> fix: ngMocks.guts reuses mock pipes

.codeclimate.yml, README.md, lib/common/core.helpers.ts, lib/common/decorate.queries.ts, lib/common/ng-mocks-universe.ts, lib/mock-builder/mock-builder.promise.ts, lib/mock-helper/func.get-from-node-element.ts, lib/mock-helper/func.get-from-node-injector.ts, lib/mock-helper/func.get-from-node-ivy.spec.ts, lib/mock-helper/func.get-from-node-ivy.ts, lib/mock-helper/func.get-from-node-scan.ts, lib/mock-helper/func.get-from-node-standard.ts, lib/mock-helper/func.get-from-node.ts, lib/mock-helper/mock-helper.find-instances.ts, lib/mock-helper/mock-helper.get.ts, lib/mock-module/mock-ng-def.ts, lib/mock-pipe/mock-pipe.ts, lib/mock-render/mock-render.ts, lib/mock-service/helper.replace-with-mocks.ts, lib/mock-service/helper.use-factory.ts, lib/mock-service/mock-provider.ts, lib/mock-service/mock-service.ts, package.release.json, tests/issue-240/fixtures.ts, tests/issue-240/test.builder.spec.ts, tests/issue-240/test.guts.spec.ts, tests/issue-240/test.nodes.spec.ts, tests/issue-240/test.real.spec.ts
=> feat: impure pipes support + `.get`, `.findInstance` can find them in fixtures

lib/common/func.get-provider.ts, lib/common/func.is-ng-injection-token.ts, lib/common/func.is-ng-module-def-with-providers.ts, lib/mock-builder/mock-builder.promise.ts, lib/mock-builder/promise/add-requested-providers.ts, lib/mock-helper/mock-helper.guts.ts, lib/mock-service/helper.resolve-provider.ts, lib/mock-service/mock-provider.ts, lib/mock/clone-providers.ts, tests/issue-248/test.spec.ts
=> fix(#248): handling null and undefined in declarations

README.md
=> docs: better info about mock services

docs/articles/troubleshooting/internals-vs-externals.md, docs/sidebars.js
=> docs(#281): information about internals vs externals

CHANGELOG.md, docs/articles/migrations.md, docs/sidebars.js
=> docs(#282): how to update to the latest version

.circleci/config.yml, docs/articles/guides/view-child.md, docs/sidebars.js, examples/TestViewChild/test.spec.ts, tests-angular/e2e/karma.conf.js
=> docs(#283): example with ViewChild and ViewChildren

tests/issue-296/test.spec.ts
=> test: covering ComponentFactoryResolver

docs/articles/api/ngMocks.md, docs/articles/api/ngMocks/find.md, docs/articles/api/ngMocks/findAll.md, docs/articles/api/ngMocks/findTemplateRef.md, docs/articles/api/ngMocks/findTemplateRefs.md, docs/sidebars.js, karma.conf.ts, libs/ng-mocks/src/lib/mock-helper/func.parse-find-args-name.ts, libs/ng-mocks/src/lib/mock-helper/func.parse-find-args.ts, libs/ng-mocks/src/lib/mock-helper/func.parse-find-term.ts, libs/ng-mocks/src/lib/mock-helper/func.parse-provider-tokens-directives.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.attributes.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.find-all.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.find-instance.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.find-instances.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.find-template-ref.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.find-template-refs.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.ts, tests/ng-mocks-find-all/test.spec.ts, tests/ng-mocks-find-instances/test.spec.ts, tests/ng-mocks-find-template-ref/test.spec.ts, tests/ng-mocks-find-template-refs/test.spec.ts, tests/ng-mocks-find/test.spec.ts
=> feat: ngMocks.findTemplateRef

libs/ng-mocks/src/lib/mock/clone-providers.ts, tests/issue-302/test.spec.ts
=> fix: cannot set property 'form' of undefined

libs/ng-mocks/src/lib/mock-helper/cva/mock-helper.change.ts, tests-angular/e2e/src/mat-input/test.spec.ts, tests/ng-mocks-change/reactive-forms.spec.ts
=> fix(#316): better support for typeIn and ngModel

libs/ng-mocks/src/lib/common/core.form.ts, libs/ng-mocks/src/lib/mock-helper/cva/func.get-vca.ts, libs/ng-mocks/src/lib/mock-helper/cva/mock-helper.change.ts, libs/ng-mocks/src/lib/mock-helper/cva/mock-helper.touch.ts, tests/ng-mocks-change/cdr.spec.ts, tests/ng-mocks-touch/cdr.spec.ts
=> fix(#320): full implementation of ngMocks.touch and ngMocks.change

README.md
=> docs(#321): better tweet

libs/ng-mocks/src/lib/common/core.reflect.provided-in.spec.ts, libs/ng-mocks/src/lib/common/core.reflect.provided-in.ts, libs/ng-mocks/src/lib/mock-builder/promise/get-root-provider-parameters.ts, libs/ng-mocks/src/lib/mock-builder/promise/handle-provided-in-dependency.ts, libs/ng-mocks/src/lib/mock-builder/promise/skip-dep.ts, tests/issue-377/e2e.spec.ts, tests/issue-377/test.spec.ts
=> fix(#377): respect of providedIn in Injectable

e2e/a5es2015/package-lock.json, e2e/a5es2015/package.json, e2e/a5es5/package-lock.json, e2e/a5es5/package.json
=> Revert "Update dependency @types/jasmine to v2.8.17"

libs/ng-mocks/src/lib/mock-builder/mock-builder.promise.ts, libs/ng-mocks/src/lib/mock-builder/promise/handle-entry-components.ts, tests/issue-296/test.spec.ts, tests/issue-333/test.spec.ts
=> fix(#333): register mock components with entryComponents

libs/ng-mocks/src/lib/common/core.define-property.ts, libs/ng-mocks/src/lib/common/mock.ts, libs/ng-mocks/src/lib/mock-builder/promise/try-mock-provider.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.stub.ts, libs/ng-mocks/src/lib/mock-service/helper.create-clone.ts, libs/ng-mocks/src/lib/mock-service/helper.define-property-descriptor.ts, libs/ng-mocks/src/lib/mock-service/helper.extract-property-descriptor.ts, libs/ng-mocks/src/lib/mock-service/helper.mock-service.ts, libs/ng-mocks/src/lib/mock-service/helper.use-factory.ts, libs/ng-mocks/src/lib/mock-service/mock-provider.ts, tests/issue-455/abstract.spec.ts, tests/issue-455/token.spec.ts, tests/ng-mocks-stub/test.spec.ts
=> fix: overrides are always precise if they are functions #455

examples/MockRender/test.spec.ts, examples/TestLifecycleHooks/test.type-without-params.spec.ts, libs/ng-mocks/src/lib/mock-render/func.generate-template.ts, libs/ng-mocks/src/lib/mock-render/func.install-prop-reader.ts, libs/ng-mocks/src/lib/mock-render/mock-render.ts, libs/ng-mocks/src/lib/mock-service/helper.create-clone.ts, libs/ng-mocks/src/lib/mock-service/helper.define-property-descriptor.ts, tests/issue-434/test.spec.ts
=> fix(mock-render): generates tpl only for provided inputs and outputs #434

docs/articles/guides/lazy-loaded-module.md, docs/sidebars.js, examples/TestLazyModule/lazy-module.ts, examples/TestLazyModule/test.spec.ts, libs/ng-mocks/src/lib/mock-builder/mock-builder.ts
=> feat(mock-builder): accepts arrays in params #386

README.md, docs/articles/api/MockRender.md, libs/ng-mocks/src/lib/mock-helper/cva/mock-helper.change.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.faster.ts, libs/ng-mocks/src/lib/mock-instance/mock-instance.ts, libs/ng-mocks/src/lib/mock-render/func.generate-template.ts, libs/ng-mocks/src/lib/mock-render/mock-render.ts, tests/issue-434/test.spec.ts, tests/issue-522/test.spec.ts, tests/ng-mocks-render/params.spec.ts
=> fix(mock-render): binds all inputs on no params #522

tests/issue-537/test.spec.ts
=> test: covering ChangeDetectionStrategy.OnPush #537

libs/ng-mocks/src/lib/mock-component/render/generate-template.ts, tests/issue-567/test.spec.ts
=> fix(core): broken query selectors are properly normalized #567

docs/articles/migrations.md, e2e/a12/package-lock.json, libs/ng-mocks/src/lib/mock-helper/mock-helper.object.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.throw-on-console.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.ts, libs/ng-mocks/src/lib/mock-render/func.create-wrapper.ts, libs/ng-mocks/src/lib/mock-render/mock-render-factory.ts, tests/issue-572/test.spec.ts, tests/ng-mocks-throw-on-console/test.spec.ts
=> fix(core): a config parameter to suppress MockRender errors #572

examples/MockBuilder/test.ng-mocks.spec.ts, libs/ng-mocks/src/lib/mock-builder/promise/add-missed-mock-declarations-and-modules.ts, libs/ng-mocks/src/lib/mock-builder/promise/try-mock-provider.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.default-mock.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.ts, libs/ng-mocks/src/lib/mock-module/mock-module.spec.ts, libs/ng-mocks/src/lib/mock-render/mock-render-factory.ts, libs/ng-mocks/src/lib/mock-render/mock-render.ts, libs/ng-mocks/src/lib/mock-service/helper.resolve-provider.ts, libs/ng-mocks/src/lib/mock-service/mock-provider.ts, tests/issue-568/test.spec.ts
=> fix(default-mock): supports an array with declarations #568

libs/ng-mocks/src/lib/mock-builder/func.extract-tokens.ts, libs/ng-mocks/src/lib/mock-builder/mock-builder.ts, libs/ng-mocks/src/lib/mock-render/func.reflect-template.ts, tests/issue-576/test.spec.ts
=> fix(faster): supports directives and components without selectors #576

libs/ng-mocks/src/lib/mock-helper/mock-helper.ts, tests/issue-568/test.spec.ts
=> fix(default-mock): supports generic type in array signature #583

docs/articles/migrations.md, libs/ng-mocks/src/lib/mock-helper/mock-helper.object.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.ts, libs/ng-mocks/src/lib/mock-render/mock-render-factory.ts, tests/issue-572/test.spec.ts
=> fix(mock-render): allowing to disable flush TestBed warning

docs/articles/credits.md, docs/sidebars.js
=> docs: credits page #587

libs/ng-mocks/src/lib/common/ng-mocks-universe.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.object.ts, libs/ng-mocks/src/lib/mock-render/mock-render-factory.ts, tests/issue-488/test.spec.ts, tests/issue-572/test.spec.ts
=> fix(mock-render): default to onTestBedFlushNeed = warn #593

docs/articles/api/MockRender.md, libs/ng-mocks/src/lib/mock-render/func.create-wrapper.ts, libs/ng-mocks/src/lib/mock-render/func.generate-template.ts, libs/ng-mocks/src/lib/mock-render/mock-render-factory.ts, libs/ng-mocks/src/lib/mock-render/mock-render.ts, tests/mock-render-factory/docs.spec.ts, tests/mock-render-factory/test.spec.ts
=> fix(mock-render): dynamic params and cdr for factory #586

.circleci/config.yml, README.md, e2e/a10/tsconfig.es2015ivy.spec.json, e2e/a10/tsconfig.es2015noivy.spec.json, e2e/a11/tsconfig.es2015ivy.spec.json, e2e/a11/tsconfig.es2015noivy.spec.json, e2e/a12/tsconfig.es2015ivy.spec.json, e2e/a9/tsconfig.es2015ivy.spec.json, e2e/a9/tsconfig.es2015noivy.spec.json
=> build(e2e): all targets

libs/ng-mocks/src/lib/mock-render/func.install-prop-reader.ts, libs/ng-mocks/src/lib/mock-render/mock-render-factory.ts, tests/issue-621/test.spec.ts
=> fix(mock-render): skipping proxy for bindings from factory #621

.editorconfig, docs/articles/guides/libraries/ngrx.md, libs/ng-mocks/src/lib/common/ng-mocks-universe.ts, package-lock.json, package.json, tests-angular/e2e/package.json, tests-angular/e2e/src/issue-589/dev-tools.spec.ts, tests-angular/e2e/src/issue-589/meta-reducers.spec.ts, tests/issue-589/test.spec.ts
=> fix(core): excluding StoreDevtoolsModule by default #589

libs/ng-mocks/src/lib/mock-builder/promise/init-modules.ts, tests/issue-625/test.spec.ts
=> fix(mock-builder): keeps and mocks modules with providers properly #625

.circleci/config.yml, docs/articles/api/MockRender.md, e2e/a10/package.json, e2e/a11/package.json, e2e/a12/package.json, e2e/a5es2015/package.json, e2e/a5es5/package.json, e2e/a6/package.json, e2e/a7/package.json, e2e/a8/package.json, e2e/a9/package.json, e2e/am/package.json, libs/ng-mocks/src/lib/common/ng-mocks-stack.ts, libs/ng-mocks/src/lib/mock-render/func.create-wrapper.ts, libs/ng-mocks/src/lib/mock-render/mock-render-factory.ts, libs/ng-mocks/src/lib/mock-render/types.ts, tests/mock-render-factory/install.spec.ts, tests/mock-render-factory/tpl.spec.ts
=> fix(mock-render): factory can be used in describes #629

libs/ng-mocks/package.json, libs/ng-mocks/src/lib/mock-helper/mock-helper.ts, package.json, tests-angular/e2e/tsconfig.json, tests-failures/mock-builder-constructor.ts, tests/issue-145/components.spec.ts, tests/issue-145/directives.spec.ts, tsconfig.esm.json, tsconfig.json
=> fix(core): building cjs and mjs #702

README.md, docs/articles/api/ngMocks/faster.md, docs/articles/index.md, docs/package-lock.json, e2e/a-min/package-lock.json, e2e/a12/package-lock.json, examples/readme/builder.spec.ts, examples/readme/classic.spec.ts, libs/ng-mocks/src/lib/mock-builder/mock-builder.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.faster-install.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.faster.ts, tests/issue-721/before-all.spec.ts, tests/issue-721/before-each.spec.ts
=> fix(faster): support for pure TestBed #721

libs/ng-mocks/src/lib/mock-builder/mock-builder.promise.ts, libs/ng-mocks/src/lib/mock-builder/mock-builder.ts, libs/ng-mocks/src/lib/mock-builder/promise/add-missing-definition.ts, libs/ng-mocks/src/lib/mock-builder/promise/add-missing-keep-declarations-and-modules.ts, libs/ng-mocks/src/lib/mock-builder/promise/add-missing-mock-declarations-and-modules.ts, libs/ng-mocks/src/lib/mock-builder/promise/parse-mock-arguments.ts, libs/ng-mocks/src/lib/mock-module/create-resolvers.ts, libs/ng-mocks/src/lib/mock-module/mark-providers.ts, libs/ng-mocks/src/lib/mock-module/mock-ng-def.ts, tests/issue-623/nested.spec.ts, tests/issue-623/test.spec.ts
=> fix(mock-builder): provides globally exported providers from directives and components #623

.circleci/config.yml, .codeclimate.yml, karma.conf.ts, libs/ng-mocks/src/lib/common/core.config.ts, libs/ng-mocks/src/lib/common/ng-mocks-universe.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.object.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.reset.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.ts, libs/ng-mocks/src/lib/mock-render/func.create-wrapper.ts, tests-performance/mock-builder.spec.ts, tests-performance/mock-render.spec.ts, tests-performance/test-bed.spec.ts, tests-performance/test.spec.ts, tests/issue-572/test.spec.ts, tsconfig.spec.json
=> perf(mock-render): caching generated component #731

libs/ng-mocks/src/lib/mock-builder/promise/handle-entry-components.ts, libs/ng-mocks/src/lib/mock-service/helper.create-clone.ts, tests/issue-736/test.spec.ts
=> fix(core): allowing spies on ComponentFactoryResolver.resolveComponentFactory #736

libs/ng-mocks/src/lib/mock-builder/mock-builder.ts, libs/ng-mocks/src/lib/mock-builder/promise/add-missing-keep-declarations-and-modules.ts, libs/ng-mocks/src/lib/mock-builder/promise/types.ts, tests-failures/mock-builder-constructor.ts, tests/issue-762/module.spec.ts, tests/issue-762/string.spec.ts, tests/issue-762/token.spec.ts
=> fix(MockBuilder): params support tokens and modules with providers #762

docs/articles/api/ngMocks.md, docs/articles/api/ngMocks/ignoreOnConsole.md, docs/articles/api/ngMocks/throwOnConsole.md, docs/sidebars.js, libs/ng-mocks/src/lib/mock-helper/mock-helper.ignore-on-console.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.object.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.ts, tests/ng-mocks-ignore-on-console/test.spec.ts
=> feat(ngMocks): allows to suppress console logs #578

e2e/a-jest/src/tests/issue-760/1.fixtures.ts, e2e/a-jest/src/tests/issue-760/2.fixtures.ts, e2e/a-jest/src/tests/issue-760/test.spec.ts, libs/ng-mocks/src/lib/common/core.reflect.body-catch.ts, libs/ng-mocks/src/lib/common/error.empty-def.spec.ts, libs/ng-mocks/src/lib/common/error.empty-def.ts, libs/ng-mocks/src/lib/common/error.jest-mock.ts, libs/ng-mocks/src/lib/common/error.missing-decorators.ts, libs/ng-mocks/src/lib/common/func.is-jest-mock.spec.ts, libs/ng-mocks/src/lib/common/func.is-jest-mock.ts, libs/ng-mocks/src/lib/mock-builder/mock-builder.promise.ts, libs/ng-mocks/src/lib/mock-builder/promise/detect-wrong-declarations.ts, libs/ng-mocks/src/lib/mock-declaration/mock-declaration.spec.ts, libs/ng-mocks/src/lib/mock-declaration/mock-declaration.ts, tests/issue-760/jest.spec.ts, tests/issue-760/no-decorators.spec.ts
=> fix(jest): better detection and error reporting of jest.mock #760

libs/ng-mocks/src/lib/common/ng-mocks-stack.ts
Add mocha runner support to the internal stack.
Closes #838
=> feat(core): internal stack integration with mocha runner

docs/articles/extra/mock-form-controls.md, docs/docusaurus.config.js, package.json
=> docs: ControlValueAccessor via properties and methods #884

docs/articles/api/MockComponent.md, docs/articles/api/MockDirective.md, docs/articles/api/MockRender.md
=> docs(MockRender): information about proxies #839

libs/ng-mocks/src/lib/resolve/collect-declarations.ts, tests/issue-1587/test.spec.ts
=> fix(core): parsing only own declarations #1587

karma.conf.ts, libs/ng-mocks/src/lib/mock/decorate-declaration.ts, tests/double-declarations/fixtures.ts, tests/double-declarations/test.spec.ts, tests/issue-1427/test.spec.ts
=> fix(core): ignoring host bindings in mocks #1427

docs/articles/api/ngMocks/globalKeep.md
=> docs: correct ref to globalKeep #1716

libs/ng-mocks/src/lib/mock-helper/crawl/nested-check-children.ts, package.json, tests/issue-1596/test.spec.ts
closes https://github.com/ike18t/ng-mocks/issues/1596
=>  fix: looking in vcr.createComponent on root node #1596

docs/articles/api/MockRender.md, docs/docusaurus.config.js, docs/package-lock.json, docs/package.json, renovate.json
=> docs(MockRender): fixture.detectChanges #1860

docs/articles/guides/mock/directive-structural-let-of.md, docs/sidebars.js, examples/TestDirectiveLetOf/dynamic.spec.ts, examples/TestDirectiveLetOf/static.spec.ts
=> docs: example of structural directives with let and of #1918

docs/articles/api/MockRender.md, libs/ng-mocks/src/lib/mock-module/mock-ng-def.ts, libs/ng-mocks/src/lib/mock-render/func.create-wrapper.ts, libs/ng-mocks/src/lib/mock-render/types.ts, tests/issue-1507/test.spec.ts, tests/mock-render-view-providers/test.spec.ts
=> fix(core): mocking viewProviders #1507

tests/issue-1957/test.spec.ts
=> test: covering #1957

libs/ng-mocks/src/lib/common/ng-mocks-universe.ts, libs/ng-mocks/src/lib/mock-instance/mock-instance-apply.ts, libs/ng-mocks/src/lib/mock-instance/mock-instance.ts, tests/issue-1256/test.spec.ts
=> feat(MockInstance): resets root overrides likewise properties #1256

libs/ng-mocks/src/lib/common/func.get-mocked-ng-def-of.ts, tests-failures/get-mocked-ng-def-of.ts
=> fix(core): generic in getMockedNgDefOf #985

renovate.json
=> build(renovate): disabling dependency dashboard #1010

docs/articles/extra/quick-start.md
=> docs: better quick start #2009

libs/ng-mocks/src/lib/mock-instance/mock-instance.ts, tests/issue-2087/test.spec.ts
=> fix(MockInstance): correctly accepts falsy values #2087

tests/issue-885/test.spec.ts
=> tests: covering reset issue #885

tests/issue-919/test.spec.ts
=> tests(MockRender): covering change detection behavior #919

libs/ng-mocks/src/lib/common/core.helpers.ts, libs/ng-mocks/src/lib/common/decorate.mock.ts, libs/ng-mocks/src/lib/common/error.jest-mock.ts, libs/ng-mocks/src/lib/common/error.missing-decorators.ts, libs/ng-mocks/src/lib/common/func.get-mocked-ng-def-of.ts, libs/ng-mocks/src/lib/common/func.get-name.spec.ts, libs/ng-mocks/src/lib/common/func.get-name.ts, libs/ng-mocks/src/lib/common/func.import-exists.ts, libs/ng-mocks/src/lib/common/ng-mocks-universe.ts, libs/ng-mocks/src/lib/mock-declaration/mock-declaration.ts, libs/ng-mocks/src/lib/mock-instance/mock-instance-forgot-reset.ts, libs/ng-mocks/src/lib/mock-module/mock-module.ts, libs/ng-mocks/src/lib/mock-pipe/mock-pipe.ts, libs/ng-mocks/src/lib/mock-service/helper.create-mock-from-prototype.ts, libs/ng-mocks/src/lib/mock-service/helper.extract-methods-from-prototype.ts, libs/ng-mocks/src/lib/mock-service/helper.mock.ts, libs/ng-mocks/src/lib/mock-service/mock-service.ts, tests/issue-1168/test.spec.ts
=> fix(core): better error messages #1168

.circleci/config.yml, libs/ng-mocks/src/lib/common/core.helpers.ts, libs/ng-mocks/src/lib/common/func.get-global.ts, libs/ng-mocks/src/lib/common/ng-mocks-global-overrides.ts, libs/ng-mocks/src/lib/common/ng-mocks-universe.ts, libs/ng-mocks/src/lib/mock-builder/mock-builder.performance.ts, libs/ng-mocks/src/lib/mock-builder/performance/add-entities-to-map.ts, libs/ng-mocks/src/lib/mock-builder/performance/add-values-to-set.ts, libs/ng-mocks/src/lib/mock-service/helper.mock-service.ts, tests-performance/ng-mocks.spec.ts
=> perf: optimizing detection of global overrides #1452

libs/ng-mocks/src/lib/mock-helper/mock-helper.stub-member.ts, libs/ng-mocks/src/lib/mock-render/func.install-prop-reader.ts, tests/issue-1165/test.spec.ts
=> fix(ngMocks.stubMember): forwarding stub values to point.componentInstance #1165

docs/articles/api/ngMocks/findInstances.md, libs/ng-mocks/src/lib/mock-helper/find-instance/mock-helper.find-instances.ts, libs/ng-mocks/src/lib/mock-helper/find/mock-helper.find-all.ts, tests/issue-1596/test.spec.ts, tests/issue-2105/test.spec.ts
=> feat(ngMocks.findInstance): looks for instances in all matched DebugElements #2105

e2e/a5es2015/package.json, e2e/a5es5/package.json, libs/ng-mocks/src/lib/mock-helper/find-instance/func.is-valid-find-instance-selector.ts, libs/ng-mocks/src/lib/mock-helper/find-instance/mock-helper.find-instance.ts, libs/ng-mocks/src/lib/mock-helper/find-instance/mock-helper.find-instances.ts, libs/ng-mocks/src/lib/mock-helper/func.get-from-node-injector.ts, libs/ng-mocks/src/lib/mock-helper/func.get-from-node.ts, libs/ng-mocks/src/lib/mock-helper/func.parse-find-args-name.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.ts, tests/issue-2097/nested.spec.ts, tests/issue-2097/test.spec.ts, tests/ng-mocks-find-instance/test.spec.ts, tests/ng-mocks-find-instances/test.spec.ts
=> feat(ngMocks.findInstance): supports tokens #2097

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
=> chore: github issue template #2088

libs/ng-mocks/src/index.ts, tests/issue-197/with-providers.spec.ts, tests/issue-271/test.spec.ts, tests/issue-312/test.spec.ts, tests/issue-589/test.spec.ts, tests/issue-625/test.spec.ts, tests/issue-762/module.spec.ts
=> fix(core): removing isNgModuleDefWithProviders from exports #2173

tests/issue-2302/test.spec.ts
=> test: covering #2302

libs/ng-mocks/src/lib/mock-helper/find-instance/mock-helper.find-instance.ts, libs/ng-mocks/src/lib/mock-helper/find-instance/mock-helper.find-instances.ts, tests/issue-2311/test.spec.ts
=> fix(ngMocks.findInstance): works without fixture #2311

.codeclimate.yml, docs/articles/api/MockProvider.md, libs/ng-mocks/src/lib/mock-builder/mock-builder.promise.ts, libs/ng-mocks/src/lib/mock-builder/promise/parse-mock-arguments.ts, libs/ng-mocks/src/lib/mock-builder/promise/try-mock-declaration.ts, libs/ng-mocks/src/lib/mock-builder/promise/try-mock-provider.ts, libs/ng-mocks/src/lib/mock-provider/mock-provider.ts, tests/mock-builder-use-class/599.spec.ts, tests/mock-provider/599.spect.ts
=> feat(MockProvider): simple generators for different types #599

.circleci/config.yml, README.md, docs/articles/api/MockRender.md, docs/articles/index.md, examples/readme/classic.spec.ts, renovate.json
=> docs(MockRender): better info about fixture and point #2362

docs/articles/api/MockRender.md, docs/articles/guides/pipe.md, examples/TestPipe/test.spec.ts, libs/ng-mocks/src/lib/common/core.helpers.ts, libs/ng-mocks/src/lib/mock-builder/mock-builder.promise.ts, libs/ng-mocks/src/lib/mock-render/func.create-wrapper.ts, libs/ng-mocks/src/lib/mock-render/func.generate-template.ts, libs/ng-mocks/src/lib/mock-render/mock-render-factory.ts, libs/ng-mocks/src/lib/mock-render/mock-render.spec.ts, libs/ng-mocks/src/lib/mock-render/mock-render.ts, tests/issue-2398/test.spec.ts, tests/issue-240/test.builder.spec.ts, tests/issue-240/test.classic.spec.ts, tests/issue-240/test.guts.spec.ts
=> fix(MockRender): renders pipes with $implicit param #2398

CHANGELOG.md, docs/articles/migrations.md
=> docs: better explanation of migration to v14 #2987

libs/ng-mocks/src/lib/mock-component/mock-component.ts, libs/ng-mocks/src/lib/mock-directive/mock-directive.ts, libs/ng-mocks/src/lib/mock/decorate-declaration.ts, tests/issue-3100/test.spec.ts
=> fix(core): detecting and mocking standalone directives correctly #3100

docs/package-lock.json, e2e/a14/package-lock.json, e2e/jasmine/package-lock.json, e2e/jest/package-lock.json, e2e/min/package-lock.json, e2e/nx/package-lock.json, libs/ng-mocks/package.json, libs/ng-mocks/src/lib/mock-builder/mock-builder.promise.ts, package-lock.json, tests-e2e/package-lock.json, tests/issue-3265/test.spec.ts
=> fix(MockBuilder): respects initial config of declarations #3265

libs/ng-mocks/src/lib/common/func.get-name.ts, libs/ng-mocks/src/lib/mock-service/mock-service.spec.ts, tests/issue-3274/test.spec.ts
=> fix(core): generates compatible function names #3274

libs/ng-mocks/src/lib/mock-builder/mock-builder.promise.ts, libs/ng-mocks/src/lib/mock-builder/types.ts
=> fix(MockBuilder): type of TestBed #3466

libs/ng-mocks/src/lib/common/func.is-jest-mock.spec.ts, libs/ng-mocks/src/lib/mock-builder/mock-builder.performance.ts, libs/ng-mocks/src/lib/mock-component/mock-component.ts, libs/ng-mocks/src/lib/mock-render/types.ts, libs/ng-mocks/src/lib/resolve/collect-declarations.ts
=> fix(core): supports TS 4.8.3 #3514

libs/ng-mocks/src/lib/mock-builder/promise/init-mock-declarations.ts, libs/ng-mocks/src/lib/mock-builder/promise/init-universe.ts, tests/issue-3635/test.spec.ts
=> fix(MockBuilder): better detection of provided dependencies #3635

libs/ng-mocks/src/lib/mock-render/func.reflect-template.ts, tests/issue-3636/test.spec.ts
=> fix(MockRender): does not throw on standalone declarations #3636

docs/articles/api/MockBuilder.md, docs/articles/extra/auto-spy.md, docs/articles/extra/with-3rd-party.md
=> docs(ngMocks.autoSpy): better explanation what it is #3687

docs/articles/api/MockInstance.md, examples/MockInstance/component.spec.ts
=> docs(MockInstance): works with legacy tools too #3391

CONTRIBUTING.md
=> docs(CONTRIBUTING): up to date info how to contribute to the project #3882

libs/ng-mocks/src/lib/mock-render/func.reflect-template.ts, tests/issue-4032/test.spec.ts
=> fix(MockRender): respecting customizations for declarations without selectors #4032

libs/ng-mocks/src/lib/common/core.types.ts, libs/ng-mocks/src/lib/mock-module/mock-ng-def.ts, tests/issue-4228/test.spec.ts
=> fix(core): respecting schemas in mock modules #4228

docs/articles/troubleshooting/read-property-of-undefined.md, tests-e2e/src/issue-4249/test.spec.ts
=> docs: how to fix mock BreakpointObserver #4249

docs/articles/api/MockBuilder.md, docs/articles/guides/route.md, docs/articles/guides/routing-guard.md, docs/articles/guides/routing-resolver.md
=> docs(RouterModule): emphasizing NG_MOCKS_ROOT_PROVIDERS #4429

libs/ng-mocks/src/lib/common/func.extract-deps.ts, libs/ng-mocks/src/lib/common/func.get-provider.ts, libs/ng-mocks/src/lib/common/func.get-type.ts, libs/ng-mocks/src/lib/common/ng-mocks-global-overrides.ts, libs/ng-mocks/src/lib/mock-builder/mock-builder.promise.ts, libs/ng-mocks/src/lib/mock-builder/performance/required-metadata.ts, libs/ng-mocks/src/lib/mock-builder/promise/add-requested-providers.ts, libs/ng-mocks/src/lib/mock-builder/promise/apply-platform-modules.ts, libs/ng-mocks/src/lib/mock-builder/promise/init-modules.ts, libs/ng-mocks/src/lib/mock-builder/promise/init-ng-modules.ts, libs/ng-mocks/src/lib/mock-builder/promise/parse-provider.ts, libs/ng-mocks/src/lib/mock-helper/func.parse-provider-tokens-directives.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.guts.ts, libs/ng-mocks/src/lib/mock-module/create-resolvers.ts, libs/ng-mocks/src/lib/mock-module/mark-providers.ts, libs/ng-mocks/src/lib/mock-module/mock-module.ts, libs/ng-mocks/src/lib/mock-module/mock-ng-def.ts, libs/ng-mocks/src/lib/mock-service/helper.resolve-provider.ts, libs/ng-mocks/src/lib/mock-service/mock-provider.ts, libs/ng-mocks/src/lib/mock/clone-providers.ts, libs/ng-mocks/src/lib/mock/decorate-declaration.ts, libs/ng-mocks/src/lib/mock/return-cached-mock.ts, tests-e2e/src/issue-4344/test.spec.ts, tests/issue-4344/standalone-explicit.spec.ts, tests/issue-4344/with-providers-explicit.spec.ts, tests/issue-4344/with-providers.spec.ts
=> feat(core): hidden usage of MockBuilder in TestBed if kept and mock modules are used together #4344

libs/ng-mocks/src/lib/common/mock.ts, libs/ng-mocks/src/lib/common/ng-mocks-global-overrides.ts, libs/ng-mocks/src/lib/mock-pipe/mock-pipe.ts, tests/issue-4564/test.spec.ts
=> fix(core): respecting transform in mock pipes #4564

examples/MockActivatedRoute/test.spec.ts, libs/ng-mocks/src/lib/common/ng-mocks-global-overrides.ts, tests/issue-4564/test.spec.ts
=> fix(core): correctly defines TestBed with multiple declarations with the same selector #4564

docs/articles/troubleshooting/faq.md, tests/issue-377/test.spec.ts
=> docs(a15): fixing FormBuilder declaration #4700

.eslintrc.yml, docs/articles/api/MockBuilder.md, libs/ng-mocks/src/lib/common/ng-mocks-global-overrides.ts, libs/ng-mocks/src/lib/mock-builder/promise/init-ng-modules.ts, libs/ng-mocks/src/lib/mock-builder/types.ts, tests/issue-4641/mixed.spec.ts, tests/issue-4641/test.spec.ts
=> fix(MockBuilder): precise exports via TestBed.configureTestingModule #4641

docs/articles/migrations.md
=> docs(a15): migration #4822

docs/articles/extra/install.md, e2e/a14/src/setup-jest.ts, e2e/a14/src/test.ts, e2e/a15/src/setup-jest.ts, e2e/a15/src/test.ts, e2e/jasmine/src/test.ts, e2e/jest/src/setup-jest.ts, e2e/nx/apps/a-nx/src/test-setup.ts, libs/ng-mocks/src/lib/common/func.iterate-declaration.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.global-exclude.spec.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.global-exclude.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.global-keep.spec.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.global-keep.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.global-mock.spec.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.global-mock.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.global-wipe.spec.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.global-wipe.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.ts, libs/ng-mocks/src/lib/mock-service/helper.resolve-provider.ts, test.ts, tests/issue-5047/test.spec.ts
=> docs(CommonModule): keeping standalone declarations #5047

libs/ng-mocks/src/lib/mock-service/helper.replace-with-mocks.ts, libs/ng-mocks/src/lib/mock-service/mock-service.ts, tests-failures/mock-service.ts, tests/issue-5262/test.spec.ts, tests/mock-service/test.spec.ts
=> fix(core): detecting self-references in mocks #5262

libs/ng-mocks/src/lib/common/func.extract-deps.ts, libs/ng-mocks/src/lib/common/ng-mocks-universe.ts, libs/ng-mocks/src/lib/mock-builder/promise/init-mock-declarations.ts, libs/ng-mocks/src/lib/mock-builder/promise/init-modules.ts, libs/ng-mocks/src/lib/mock-builder/promise/init-universe.ts, libs/ng-mocks/src/lib/mock-builder/promise/try-mock-declaration.ts, libs/ng-mocks/src/lib/mock-pipe/mock-pipe.ts, tests-e2e/src/issue-5239/test.spec.ts, tests/issue-5239/test.spec.ts
=> Bug: dependencies of a mock take precedence over root mocks #5239

.eslintrc.yml, docs/articles/guides/host-directive.md, docs/articles/guides/mock/host-directive.md, docs/sidebars.js, examples/MockHostDirective/test.spec.ts, examples/TestHostDirective/test.spec.ts, libs/ng-mocks/src/lib/common/core.config.ts, libs/ng-mocks/src/lib/common/core.types.ts, libs/ng-mocks/src/lib/common/func.get-type.ts, libs/ng-mocks/src/lib/mock-module/mock-ng-def.ts, libs/ng-mocks/src/lib/mock-render/func.create-wrapper.ts, libs/ng-mocks/src/lib/mock/decorate-declaration.ts, tests/issue-5117/base.spec.ts, tests/issue-5117/coverage.spec.ts, tests/issue-5117/input.spec.ts, tests/issue-5117/output.spec.ts, tests/issue-5117/test.spec.ts
=> feat(core): support of HostDirectives #5117

docs/articles/guides/mock/initialization-logic.md, docs/sidebars.js, examples/MockInitializationLogic/test.spec.ts
=> docs: how to mock dependencies of initialization logic #5583

docs/articles/api/MockInstance.md, libs/ng-mocks/src/lib/mock-instance/mock-instance.ts, tests/issue-5537/test.spec.ts
=> fix(MockInstance): multi-token and multi-service #5585

.eslintrc.yml, docs/articles/api/MockBuilder.md, libs/ng-mocks/src/index.ts, libs/ng-mocks/src/lib/mock-builder/mock-builder.ts, libs/ng-mocks/src/lib/mock-builder/types.ts, tests/issue-5417/test.spec.ts
=> feat(MockBuilder): can be extended with custom methods #5417

.circleci/config.yml
=> fix(ci): running npm after nvm #6505

CONTRIBUTING.md
=> docs: guide how to add support of new angular versions #7215

docs/articles/credits.md, docs/articles/guides.md, docs/articles/guides/route.md, docs/articles/need-help.md, docs/articles/tl-dr.md
=> docs: typos #7093

libs/ng-mocks/src/index.ts, libs/ng-mocks/src/lib/mock-builder/mock-builder.promise.ts, libs/ng-mocks/src/lib/mock-builder/promise/types.ts, libs/ng-mocks/src/lib/mock-builder/types.ts, tests-failures/mock-builder-provide.ts
=> feat(MockBuilder): supports EnvironmentProviders #7011

libs/ng-mocks/src/lib/mock-helper/find-instance/mock-helper.find-instance.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.get.ts, tests/issue-7041/test.spec.ts
=> fix(ngMocks): respects custom errors on lookups #7041

docs/articles/troubleshooting/browser-animations-module.md
=> docs(BrowserAnimationsModule): an example how to write tests #7466

libs/ng-mocks/src/lib/common/ng-mocks-universe.ts, libs/ng-mocks/src/lib/mock-builder/promise/init-module.ts, libs/ng-mocks/src/lib/mock-builder/promise/init-ng-modules.ts, libs/ng-mocks/src/lib/mock-module/mark-providers.ts, libs/ng-mocks/src/lib/mock-module/mock-ng-def.ts, libs/ng-mocks/src/lib/mock/mark-exported.ts, tests/issue-6928/test.spec.ts
=> fix(core): respecting the order of declaration in TestBed #6928

docs/articles/extra/mock-form-controls.md, docs/articles/extra/sanitizer.md
=> docs(NgModel): enhanced description #7491

libs/ng-mocks/package.json
=> chore(root): updated funding link to sponsors/help-me-mom

README.md, docs/articles/index.md, docs/docusaurus.config.js, package.json
=> chore(root): updated links to help-me-mom repository

.circleci/config.yml
=> build(ci): fail on package-lock.json sync issues #9111

libs/ng-mocks/src/lib/mock-helper/crawl/crawl-by-attribute-value.ts
=> fix(ngMocks.findTemplateRef): detects NgTemplates correctly

libs/ng-mocks/src/lib/common/core.config.ts, libs/ng-mocks/src/lib/common/func.is-standalone.ts, libs/ng-mocks/src/lib/common/ng-mocks-universe.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.object.ts, libs/ng-mocks/src/lib/mock-helper/mock-helper.ts, libs/ng-mocks/src/lib/mock-render/func.reflect-template.ts, tests-e2e/package-lock.json, tests-e2e/package.json, tests-e2e/src/ngx-translate/test.spec.ts
fixes #10752
closes #10819
closes #10826
fixes #11097
=> fix(core): standalone optimization and ngx-translate e2e integration #10752

tests-e2e/src/issue-10762/ngx-translate.spec.ts
Added an extra test case to verify if the issue is resolved. I saw locally the test failed when using v14.13.2 and it passes with v14.13.3 and higher.
Feel free to review / merge or close the PR
=> test(ngx-translate): added an extra test case

libs/ng-mocks/src/lib/mock-render/mock-render-factory.ts, tests/issue-11324/test.spec.ts
=> fix: respect TestBed teardown
